# -*- coding: utf-8 -*-
"""Track_b_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpLNDFYAsUcJZ_LhdGE3yKXdHdYTdW0w
"""

pip install -U sentence-transformers numpy pandas

import json
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

with open("track_b_data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

story_ids = []
stories = []

for item in data:
    story_ids.append(item["story_id"])
    stories.append(item["story_text"])

#text cleaning
def clean_text(text):
    text = text.lower()
    text = text.replace("\n", " ")
    text = " ".join(text.split())
    return text

stories = [clean_text(s) for s in stories]

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(
    stories,
    batch_size=32,
    convert_to_numpy=True,
    normalize_embeddings=True
)

from sentence_transformers.util import cos_sim

print(cos_sim(embeddings[0], embeddings[0]))   # ~1.0
print(cos_sim(embeddings[0], embeddings[1]))   # lower value

output = []

for sid, emb in zip(story_ids, embeddings):
    output.append({
        "story_id": sid,
        "embedding": emb.tolist()
    })

with open("track_b_baseline_embeddings.json", "w") as f:
    json.dump(output, f)