# -*- coding: utf-8 -*-
"""track_b_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vpw_IBGtSGH-1qtFGhCW0RivNaTwPBCj
"""

!pip install -U sentence-transformers torch

import random
import json
import torch
import numpy as np
from sentence_transformers import SentenceTransformer,InputExample,losses
from torch.utils.data import DataLoader

#load data set for training
train_data = []

with open("/content/synthetic_data_for_classification (1).jsonl", "r", encoding="utf-8") as f:
    for line in f:
        train_data.append(json.loads(line))

#light preprocessing
def clean_text(text):
  text=text.lower()
  text=" ".join(text.split())
  return text

train_examples = []

for item in train_data:
    # Skip broken rows safely
    if item["anchor_text"] is None or item["text_a"] is None or item["text_b"] is None:
        continue

    anchor = clean_text(item["anchor_text"])
    a = clean_text(item["text_a"])
    b = clean_text(item["text_b"])

    if item["text_a_is_closer"] is True:
        positive, negative = a, b
    else:
        positive, negative = b, a

    train_examples.append(
        InputExample(texts=[anchor, positive, negative])
    )

model = SentenceTransformer("all-MiniLM-L6-v2")

#defining triplet loss
train_loss=losses.TripletLoss(
    model=model,
    distance_metric=losses.TripletDistanceMetric.COSINE,
    triplet_margin=0.3
    #A margin of 0.3 enforces a meaningful separation between similar and dissimilar narratives while remaining stable for training on noisy narrative similarity data.”
)

#dataloader
train_dataloader=DataLoader(
    train_examples,
    shuffle=True,
    batch_size=16
)

#finetuning
model.fit(
    train_objectives=[(train_dataloader,train_loss)],
    epochs=1,  #prevents overfitting
    warmup_steps=100,
    show_progress_bar=True

)

#encode track-b data
with open("/content/dev_track_b.jsonl", "r", encoding="utf-8") as f:
    trackB_dev = json.load(f)

dev_texts = [clean_text(item["text"]) for item in trackB_dev]

#convert to embedings
dev_embeddings = model.encode(
    dev_texts,
    convert_to_numpy=True,
    show_progress_bar=True
)

with open("trackB_test.json", "r", encoding="utf-8") as f:
    trackB_test = json.load(f)

test_texts = [clean_text(item["text"]) for item in trackB_test]

test_embeddings = model.encode(
    test_texts,
    convert_to_numpy=True,
    show_progress_bar=True
)

np.save("trackB_submission_embeddings.npy", test_embeddings)



